// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 2034610273;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__safety__classify_bytes_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "classify_bytes",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_bytes = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_safety = <crate::api::types::SafetyOptions>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::ImageGuardError>((move || {
                    let output_ok = crate::api::safety::classify_bytes(api_bytes, api_safety)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__safety__classify_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "classify_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            let api_safety = <crate::api::types::SafetyOptions>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::ImageGuardError>((move || {
                    let output_ok = crate::api::safety::classify_file(api_path, api_safety)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__compress__compress_bytes_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "compress_bytes",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_bytes = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_options = <crate::api::types::CompressOptions>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::ImageGuardError>((move || {
                    let output_ok = crate::api::compress::compress_bytes(api_bytes, api_options)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__compress__compress_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "compress_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            let api_options = <crate::api::types::CompressOptions>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::ImageGuardError>((move || {
                    let output_ok = crate::api::compress::compress_file(api_path, api_options)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__types__compress_options_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "compress_options_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>(crate::api::types::CompressOptions::default())?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__compress__image_info_bytes_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "image_info_bytes",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_bytes = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::ImageGuardError>((move || {
                    let output_ok = crate::api::compress::image_info_bytes(api_bytes)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__compress__image_info_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "image_info_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::ImageGuardError>((move || {
                    let output_ok = crate::api::compress::image_info_file(api_path)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__compress__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::compress::init_app();
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__safety__is_model_loaded_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "is_model_loaded",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::safety::is_model_loaded())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__safety__load_model_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "load_model",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_model = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::ImageGuardError>((move || {
                    let output_ok = crate::api::safety::load_model(api_model)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__safety__process_bytes_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "process_bytes",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_bytes = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_options = <crate::api::types::CompressOptions>::sse_decode(&mut deserializer);
            let api_safety = <crate::api::types::SafetyOptions>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::ImageGuardError>((move || {
                    let output_ok =
                        crate::api::safety::process_bytes(api_bytes, api_options, api_safety)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__safety__process_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "process_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            let api_options = <crate::api::types::CompressOptions>::sse_decode(&mut deserializer);
            let api_safety = <crate::api::types::SafetyOptions>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::ImageGuardError>((move || {
                    let output_ok =
                        crate::api::safety::process_file(api_path, api_options, api_safety)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__types__safety_options_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "safety_options_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>(crate::api::types::SafetyOptions::default())?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__safety__unload_model_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "unload_model",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>({
                    crate::api::safety::unload_model();
                })?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__compress__validate_compress_options_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "validate_compress_options",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_options = <crate::api::types::CompressOptions>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::api::types::ImageGuardError>((move || {
                let output_ok = crate::api::compress::validate_compress_options(api_options)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::types::CompressOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_maxBytes = <u32>::sse_decode(deserializer);
        let mut var_maxWidth = <Option<u32>>::sse_decode(deserializer);
        let mut var_maxHeight = <Option<u32>>::sse_decode(deserializer);
        let mut var_format = <crate::api::types::OutputFormat>::sse_decode(deserializer);
        let mut var_minQuality = <u8>::sse_decode(deserializer);
        let mut var_maxQuality = <u8>::sse_decode(deserializer);
        let mut var_minDimension = <u32>::sse_decode(deserializer);
        let mut var_keepOriginalIfFits = <bool>::sse_decode(deserializer);
        let mut var_stripMetadata = <bool>::sse_decode(deserializer);
        return crate::api::types::CompressOptions {
            max_bytes: var_maxBytes,
            max_width: var_maxWidth,
            max_height: var_maxHeight,
            format: var_format,
            min_quality: var_minQuality,
            max_quality: var_maxQuality,
            min_dimension: var_minDimension,
            keep_original_if_fits: var_keepOriginalIfFits,
            strip_metadata: var_stripMetadata,
        };
    }
}

impl SseDecode for crate::api::types::CompressResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_bytes = <Vec<u8>>::sse_decode(deserializer);
        let mut var_sizeBytes = <u32>::sse_decode(deserializer);
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        let mut var_format = <crate::api::types::OutputFormat>::sse_decode(deserializer);
        let mut var_quality = <Option<u8>>::sse_decode(deserializer);
        let mut var_originalSizeBytes = <u32>::sse_decode(deserializer);
        let mut var_originalWidth = <u32>::sse_decode(deserializer);
        let mut var_originalHeight = <u32>::sse_decode(deserializer);
        let mut var_originalFormat = <crate::api::types::InputFormat>::sse_decode(deserializer);
        let mut var_keptOriginal = <bool>::sse_decode(deserializer);
        let mut var_attempts = <u32>::sse_decode(deserializer);
        let mut var_elapsedMs = <u32>::sse_decode(deserializer);
        return crate::api::types::CompressResult {
            bytes: var_bytes,
            size_bytes: var_sizeBytes,
            width: var_width,
            height: var_height,
            format: var_format,
            quality: var_quality,
            original_size_bytes: var_originalSizeBytes,
            original_width: var_originalWidth,
            original_height: var_originalHeight,
            original_format: var_originalFormat,
            kept_original: var_keptOriginal,
            attempts: var_attempts,
            elapsed_ms: var_elapsedMs,
        };
    }
}

impl SseDecode for crate::api::types::ErrorCode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::types::ErrorCode::InvalidOptions,
            1 => crate::api::types::ErrorCode::EmptyInput,
            2 => crate::api::types::ErrorCode::FileNotFound,
            3 => crate::api::types::ErrorCode::FileReadFailed,
            4 => crate::api::types::ErrorCode::InputTooLarge,
            5 => crate::api::types::ErrorCode::UnsupportedFormat,
            6 => crate::api::types::ErrorCode::CorruptImage,
            7 => crate::api::types::ErrorCode::ImageTooLarge,
            8 => crate::api::types::ErrorCode::CannotMeetTarget,
            9 => crate::api::types::ErrorCode::EncodingFailed,
            10 => crate::api::types::ErrorCode::ModelNotLoaded,
            11 => crate::api::types::ErrorCode::ModelLoadFailed,
            12 => crate::api::types::ErrorCode::Internal,
            _ => unreachable!("Invalid variant for ErrorCode: {}", inner),
        };
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::types::ImageGuardError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_code = <crate::api::types::ErrorCode>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        return crate::api::types::ImageGuardError {
            code: var_code,
            message: var_message,
        };
    }
}

impl SseDecode for crate::api::types::ImageInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_format = <crate::api::types::InputFormat>::sse_decode(deserializer);
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        let mut var_sizeBytes = <u32>::sse_decode(deserializer);
        let mut var_hasOrientation = <bool>::sse_decode(deserializer);
        return crate::api::types::ImageInfo {
            format: var_format,
            width: var_width,
            height: var_height,
            size_bytes: var_sizeBytes,
            has_orientation: var_hasOrientation,
        };
    }
}

impl SseDecode for crate::api::types::InputFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::types::InputFormat::Jpeg,
            1 => crate::api::types::InputFormat::Png,
            2 => crate::api::types::InputFormat::WebP,
            3 => crate::api::types::InputFormat::Gif,
            4 => crate::api::types::InputFormat::Bmp,
            _ => unreachable!("Invalid variant for InputFormat: {}", inner),
        };
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<crate::api::types::CompressResult> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::types::CompressResult>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u8>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::types::OutputFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::types::OutputFormat::Jpeg,
            1 => crate::api::types::OutputFormat::Png,
            _ => unreachable!("Invalid variant for OutputFormat: {}", inner),
        };
    }
}

impl SseDecode for crate::api::types::ProcessResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_safety = <crate::api::types::SafetyReport>::sse_decode(deserializer);
        let mut var_image = <Option<crate::api::types::CompressResult>>::sse_decode(deserializer);
        return crate::api::types::ProcessResult {
            safety: var_safety,
            image: var_image,
        };
    }
}

impl SseDecode for crate::api::types::SafetyOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_rejectThreshold = <f32>::sse_decode(deserializer);
        let mut var_reviewThreshold = <f32>::sse_decode(deserializer);
        let mut var_suggestiveWeight = <f32>::sse_decode(deserializer);
        let mut var_compressUnsafe = <bool>::sse_decode(deserializer);
        return crate::api::types::SafetyOptions {
            reject_threshold: var_rejectThreshold,
            review_threshold: var_reviewThreshold,
            suggestive_weight: var_suggestiveWeight,
            compress_unsafe: var_compressUnsafe,
        };
    }
}

impl SseDecode for crate::api::types::SafetyReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_verdict = <crate::api::types::Verdict>::sse_decode(deserializer);
        let mut var_nsfwScore = <f32>::sse_decode(deserializer);
        let mut var_scores = <crate::api::types::SafetyScores>::sse_decode(deserializer);
        let mut var_elapsedMs = <u32>::sse_decode(deserializer);
        return crate::api::types::SafetyReport {
            verdict: var_verdict,
            nsfw_score: var_nsfwScore,
            scores: var_scores,
            elapsed_ms: var_elapsedMs,
        };
    }
}

impl SseDecode for crate::api::types::SafetyScores {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_drawings = <f32>::sse_decode(deserializer);
        let mut var_hentai = <f32>::sse_decode(deserializer);
        let mut var_neutral = <f32>::sse_decode(deserializer);
        let mut var_porn = <f32>::sse_decode(deserializer);
        let mut var_sexy = <f32>::sse_decode(deserializer);
        return crate::api::types::SafetyScores {
            drawings: var_drawings,
            hentai: var_hentai,
            neutral: var_neutral,
            porn: var_porn,
            sexy: var_sexy,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::types::Verdict {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::types::Verdict::Safe,
            1 => crate::api::types::Verdict::Uncertain,
            2 => crate::api::types::Verdict::Unsafe,
            _ => unreachable!("Invalid variant for Verdict: {}", inner),
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__safety__classify_bytes_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__safety__classify_file_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__compress__compress_bytes_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__compress__compress_file_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__types__compress_options_default_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        6 => wire__crate__api__compress__image_info_bytes_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__compress__image_info_file_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__compress__init_app_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__safety__load_model_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__safety__process_bytes_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__crate__api__safety__process_file_impl(port, ptr, rust_vec_len, data_len),
        13 => {
            wire__crate__api__types__safety_options_default_impl(port, ptr, rust_vec_len, data_len)
        }
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        9 => wire__crate__api__safety__is_model_loaded_impl(ptr, rust_vec_len, data_len),
        14 => wire__crate__api__safety__unload_model_impl(ptr, rust_vec_len, data_len),
        15 => {
            wire__crate__api__compress__validate_compress_options_impl(ptr, rust_vec_len, data_len)
        }
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::CompressOptions {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.max_bytes.into_into_dart().into_dart(),
            self.max_width.into_into_dart().into_dart(),
            self.max_height.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
            self.min_quality.into_into_dart().into_dart(),
            self.max_quality.into_into_dart().into_dart(),
            self.min_dimension.into_into_dart().into_dart(),
            self.keep_original_if_fits.into_into_dart().into_dart(),
            self.strip_metadata.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::CompressOptions
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::CompressOptions>
    for crate::api::types::CompressOptions
{
    fn into_into_dart(self) -> crate::api::types::CompressOptions {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::CompressResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.bytes.into_into_dart().into_dart(),
            self.size_bytes.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
            self.quality.into_into_dart().into_dart(),
            self.original_size_bytes.into_into_dart().into_dart(),
            self.original_width.into_into_dart().into_dart(),
            self.original_height.into_into_dart().into_dart(),
            self.original_format.into_into_dart().into_dart(),
            self.kept_original.into_into_dart().into_dart(),
            self.attempts.into_into_dart().into_dart(),
            self.elapsed_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::CompressResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::CompressResult>
    for crate::api::types::CompressResult
{
    fn into_into_dart(self) -> crate::api::types::CompressResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ErrorCode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::InvalidOptions => 0.into_dart(),
            Self::EmptyInput => 1.into_dart(),
            Self::FileNotFound => 2.into_dart(),
            Self::FileReadFailed => 3.into_dart(),
            Self::InputTooLarge => 4.into_dart(),
            Self::UnsupportedFormat => 5.into_dart(),
            Self::CorruptImage => 6.into_dart(),
            Self::ImageTooLarge => 7.into_dart(),
            Self::CannotMeetTarget => 8.into_dart(),
            Self::EncodingFailed => 9.into_dart(),
            Self::ModelNotLoaded => 10.into_dart(),
            Self::ModelLoadFailed => 11.into_dart(),
            Self::Internal => 12.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::ErrorCode {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ErrorCode>
    for crate::api::types::ErrorCode
{
    fn into_into_dart(self) -> crate::api::types::ErrorCode {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ImageGuardError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.code.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::ImageGuardError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ImageGuardError>
    for crate::api::types::ImageGuardError
{
    fn into_into_dart(self) -> crate::api::types::ImageGuardError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ImageInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.format.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.size_bytes.into_into_dart().into_dart(),
            self.has_orientation.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::ImageInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ImageInfo>
    for crate::api::types::ImageInfo
{
    fn into_into_dart(self) -> crate::api::types::ImageInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::InputFormat {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Jpeg => 0.into_dart(),
            Self::Png => 1.into_dart(),
            Self::WebP => 2.into_dart(),
            Self::Gif => 3.into_dart(),
            Self::Bmp => 4.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::InputFormat
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::InputFormat>
    for crate::api::types::InputFormat
{
    fn into_into_dart(self) -> crate::api::types::InputFormat {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::OutputFormat {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Jpeg => 0.into_dart(),
            Self::Png => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::OutputFormat
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::OutputFormat>
    for crate::api::types::OutputFormat
{
    fn into_into_dart(self) -> crate::api::types::OutputFormat {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ProcessResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.safety.into_into_dart().into_dart(),
            self.image.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::ProcessResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ProcessResult>
    for crate::api::types::ProcessResult
{
    fn into_into_dart(self) -> crate::api::types::ProcessResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::SafetyOptions {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.reject_threshold.into_into_dart().into_dart(),
            self.review_threshold.into_into_dart().into_dart(),
            self.suggestive_weight.into_into_dart().into_dart(),
            self.compress_unsafe.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::SafetyOptions
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::SafetyOptions>
    for crate::api::types::SafetyOptions
{
    fn into_into_dart(self) -> crate::api::types::SafetyOptions {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::SafetyReport {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.verdict.into_into_dart().into_dart(),
            self.nsfw_score.into_into_dart().into_dart(),
            self.scores.into_into_dart().into_dart(),
            self.elapsed_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::SafetyReport
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::SafetyReport>
    for crate::api::types::SafetyReport
{
    fn into_into_dart(self) -> crate::api::types::SafetyReport {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::SafetyScores {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.drawings.into_into_dart().into_dart(),
            self.hentai.into_into_dart().into_dart(),
            self.neutral.into_into_dart().into_dart(),
            self.porn.into_into_dart().into_dart(),
            self.sexy.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::SafetyScores
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::SafetyScores>
    for crate::api::types::SafetyScores
{
    fn into_into_dart(self) -> crate::api::types::SafetyScores {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::Verdict {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Safe => 0.into_dart(),
            Self::Uncertain => 1.into_dart(),
            Self::Unsafe => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::Verdict {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::Verdict> for crate::api::types::Verdict {
    fn into_into_dart(self) -> crate::api::types::Verdict {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::types::CompressOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.max_bytes, serializer);
        <Option<u32>>::sse_encode(self.max_width, serializer);
        <Option<u32>>::sse_encode(self.max_height, serializer);
        <crate::api::types::OutputFormat>::sse_encode(self.format, serializer);
        <u8>::sse_encode(self.min_quality, serializer);
        <u8>::sse_encode(self.max_quality, serializer);
        <u32>::sse_encode(self.min_dimension, serializer);
        <bool>::sse_encode(self.keep_original_if_fits, serializer);
        <bool>::sse_encode(self.strip_metadata, serializer);
    }
}

impl SseEncode for crate::api::types::CompressResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.bytes, serializer);
        <u32>::sse_encode(self.size_bytes, serializer);
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
        <crate::api::types::OutputFormat>::sse_encode(self.format, serializer);
        <Option<u8>>::sse_encode(self.quality, serializer);
        <u32>::sse_encode(self.original_size_bytes, serializer);
        <u32>::sse_encode(self.original_width, serializer);
        <u32>::sse_encode(self.original_height, serializer);
        <crate::api::types::InputFormat>::sse_encode(self.original_format, serializer);
        <bool>::sse_encode(self.kept_original, serializer);
        <u32>::sse_encode(self.attempts, serializer);
        <u32>::sse_encode(self.elapsed_ms, serializer);
    }
}

impl SseEncode for crate::api::types::ErrorCode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::types::ErrorCode::InvalidOptions => 0,
                crate::api::types::ErrorCode::EmptyInput => 1,
                crate::api::types::ErrorCode::FileNotFound => 2,
                crate::api::types::ErrorCode::FileReadFailed => 3,
                crate::api::types::ErrorCode::InputTooLarge => 4,
                crate::api::types::ErrorCode::UnsupportedFormat => 5,
                crate::api::types::ErrorCode::CorruptImage => 6,
                crate::api::types::ErrorCode::ImageTooLarge => 7,
                crate::api::types::ErrorCode::CannotMeetTarget => 8,
                crate::api::types::ErrorCode::EncodingFailed => 9,
                crate::api::types::ErrorCode::ModelNotLoaded => 10,
                crate::api::types::ErrorCode::ModelLoadFailed => 11,
                crate::api::types::ErrorCode::Internal => 12,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::types::ImageGuardError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::types::ErrorCode>::sse_encode(self.code, serializer);
        <String>::sse_encode(self.message, serializer);
    }
}

impl SseEncode for crate::api::types::ImageInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::types::InputFormat>::sse_encode(self.format, serializer);
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
        <u32>::sse_encode(self.size_bytes, serializer);
        <bool>::sse_encode(self.has_orientation, serializer);
    }
}

impl SseEncode for crate::api::types::InputFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::types::InputFormat::Jpeg => 0,
                crate::api::types::InputFormat::Png => 1,
                crate::api::types::InputFormat::WebP => 2,
                crate::api::types::InputFormat::Gif => 3,
                crate::api::types::InputFormat::Bmp => 4,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::types::CompressResult> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::types::CompressResult>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u8>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::types::OutputFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::types::OutputFormat::Jpeg => 0,
                crate::api::types::OutputFormat::Png => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::types::ProcessResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::types::SafetyReport>::sse_encode(self.safety, serializer);
        <Option<crate::api::types::CompressResult>>::sse_encode(self.image, serializer);
    }
}

impl SseEncode for crate::api::types::SafetyOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f32>::sse_encode(self.reject_threshold, serializer);
        <f32>::sse_encode(self.review_threshold, serializer);
        <f32>::sse_encode(self.suggestive_weight, serializer);
        <bool>::sse_encode(self.compress_unsafe, serializer);
    }
}

impl SseEncode for crate::api::types::SafetyReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::types::Verdict>::sse_encode(self.verdict, serializer);
        <f32>::sse_encode(self.nsfw_score, serializer);
        <crate::api::types::SafetyScores>::sse_encode(self.scores, serializer);
        <u32>::sse_encode(self.elapsed_ms, serializer);
    }
}

impl SseEncode for crate::api::types::SafetyScores {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f32>::sse_encode(self.drawings, serializer);
        <f32>::sse_encode(self.hentai, serializer);
        <f32>::sse_encode(self.neutral, serializer);
        <f32>::sse_encode(self.porn, serializer);
        <f32>::sse_encode(self.sexy, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::types::Verdict {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::types::Verdict::Safe => 0,
                crate::api::types::Verdict::Uncertain => 1,
                crate::api::types::Verdict::Unsafe => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
