// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/compress.dart';
import 'api/safety.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiCompressInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 2034610273;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'image_guard',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<SafetyReport> crateApiSafetyClassifyBytes({
    required List<int> bytes,
    required SafetyOptions safety,
  });

  Future<SafetyReport> crateApiSafetyClassifyFile({
    required String path,
    required SafetyOptions safety,
  });

  Future<CompressResult> crateApiCompressCompressBytes({
    required List<int> bytes,
    required CompressOptions options,
  });

  Future<CompressResult> crateApiCompressCompressFile({
    required String path,
    required CompressOptions options,
  });

  Future<CompressOptions> crateApiTypesCompressOptionsDefault();

  Future<ImageInfo> crateApiCompressImageInfoBytes({required List<int> bytes});

  Future<ImageInfo> crateApiCompressImageInfoFile({required String path});

  Future<void> crateApiCompressInitApp();

  bool crateApiSafetyIsModelLoaded();

  Future<void> crateApiSafetyLoadModel({required List<int> model});

  Future<ProcessResult> crateApiSafetyProcessBytes({
    required List<int> bytes,
    required CompressOptions options,
    required SafetyOptions safety,
  });

  Future<ProcessResult> crateApiSafetyProcessFile({
    required String path,
    required CompressOptions options,
    required SafetyOptions safety,
  });

  Future<SafetyOptions> crateApiTypesSafetyOptionsDefault();

  void crateApiSafetyUnloadModel();

  void crateApiCompressValidateCompressOptions({
    required CompressOptions options,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<SafetyReport> crateApiSafetyClassifyBytes({
    required List<int> bytes,
    required SafetyOptions safety,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_box_autoadd_safety_options(safety, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_safety_report,
          decodeErrorData: sse_decode_image_guard_error,
        ),
        constMeta: kCrateApiSafetyClassifyBytesConstMeta,
        argValues: [bytes, safety],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSafetyClassifyBytesConstMeta =>
      const TaskConstMeta(
        debugName: "classify_bytes",
        argNames: ["bytes", "safety"],
      );

  @override
  Future<SafetyReport> crateApiSafetyClassifyFile({
    required String path,
    required SafetyOptions safety,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_box_autoadd_safety_options(safety, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_safety_report,
          decodeErrorData: sse_decode_image_guard_error,
        ),
        constMeta: kCrateApiSafetyClassifyFileConstMeta,
        argValues: [path, safety],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSafetyClassifyFileConstMeta => const TaskConstMeta(
    debugName: "classify_file",
    argNames: ["path", "safety"],
  );

  @override
  Future<CompressResult> crateApiCompressCompressBytes({
    required List<int> bytes,
    required CompressOptions options,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_box_autoadd_compress_options(options, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_compress_result,
          decodeErrorData: sse_decode_image_guard_error,
        ),
        constMeta: kCrateApiCompressCompressBytesConstMeta,
        argValues: [bytes, options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCompressCompressBytesConstMeta =>
      const TaskConstMeta(
        debugName: "compress_bytes",
        argNames: ["bytes", "options"],
      );

  @override
  Future<CompressResult> crateApiCompressCompressFile({
    required String path,
    required CompressOptions options,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_box_autoadd_compress_options(options, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_compress_result,
          decodeErrorData: sse_decode_image_guard_error,
        ),
        constMeta: kCrateApiCompressCompressFileConstMeta,
        argValues: [path, options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCompressCompressFileConstMeta =>
      const TaskConstMeta(
        debugName: "compress_file",
        argNames: ["path", "options"],
      );

  @override
  Future<CompressOptions> crateApiTypesCompressOptionsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_compress_options,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesCompressOptionsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesCompressOptionsDefaultConstMeta =>
      const TaskConstMeta(debugName: "compress_options_default", argNames: []);

  @override
  Future<ImageInfo> crateApiCompressImageInfoBytes({required List<int> bytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_info,
          decodeErrorData: sse_decode_image_guard_error,
        ),
        constMeta: kCrateApiCompressImageInfoBytesConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCompressImageInfoBytesConstMeta =>
      const TaskConstMeta(debugName: "image_info_bytes", argNames: ["bytes"]);

  @override
  Future<ImageInfo> crateApiCompressImageInfoFile({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_info,
          decodeErrorData: sse_decode_image_guard_error,
        ),
        constMeta: kCrateApiCompressImageInfoFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCompressImageInfoFileConstMeta =>
      const TaskConstMeta(debugName: "image_info_file", argNames: ["path"]);

  @override
  Future<void> crateApiCompressInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCompressInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCompressInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiSafetyIsModelLoaded() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSafetyIsModelLoadedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSafetyIsModelLoadedConstMeta =>
      const TaskConstMeta(debugName: "is_model_loaded", argNames: []);

  @override
  Future<void> crateApiSafetyLoadModel({required List<int> model}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(model, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_image_guard_error,
        ),
        constMeta: kCrateApiSafetyLoadModelConstMeta,
        argValues: [model],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSafetyLoadModelConstMeta =>
      const TaskConstMeta(debugName: "load_model", argNames: ["model"]);

  @override
  Future<ProcessResult> crateApiSafetyProcessBytes({
    required List<int> bytes,
    required CompressOptions options,
    required SafetyOptions safety,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_box_autoadd_compress_options(options, serializer);
          sse_encode_box_autoadd_safety_options(safety, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_process_result,
          decodeErrorData: sse_decode_image_guard_error,
        ),
        constMeta: kCrateApiSafetyProcessBytesConstMeta,
        argValues: [bytes, options, safety],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSafetyProcessBytesConstMeta => const TaskConstMeta(
    debugName: "process_bytes",
    argNames: ["bytes", "options", "safety"],
  );

  @override
  Future<ProcessResult> crateApiSafetyProcessFile({
    required String path,
    required CompressOptions options,
    required SafetyOptions safety,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_box_autoadd_compress_options(options, serializer);
          sse_encode_box_autoadd_safety_options(safety, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_process_result,
          decodeErrorData: sse_decode_image_guard_error,
        ),
        constMeta: kCrateApiSafetyProcessFileConstMeta,
        argValues: [path, options, safety],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSafetyProcessFileConstMeta => const TaskConstMeta(
    debugName: "process_file",
    argNames: ["path", "options", "safety"],
  );

  @override
  Future<SafetyOptions> crateApiTypesSafetyOptionsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_safety_options,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesSafetyOptionsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesSafetyOptionsDefaultConstMeta =>
      const TaskConstMeta(debugName: "safety_options_default", argNames: []);

  @override
  void crateApiSafetyUnloadModel() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSafetyUnloadModelConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSafetyUnloadModelConstMeta =>
      const TaskConstMeta(debugName: "unload_model", argNames: []);

  @override
  void crateApiCompressValidateCompressOptions({
    required CompressOptions options,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_compress_options(options, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_image_guard_error,
        ),
        constMeta: kCrateApiCompressValidateCompressOptionsConstMeta,
        argValues: [options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCompressValidateCompressOptionsConstMeta =>
      const TaskConstMeta(
        debugName: "validate_compress_options",
        argNames: ["options"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CompressOptions dco_decode_box_autoadd_compress_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_compress_options(raw);
  }

  @protected
  CompressResult dco_decode_box_autoadd_compress_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_compress_result(raw);
  }

  @protected
  SafetyOptions dco_decode_box_autoadd_safety_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_safety_options(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CompressOptions dco_decode_compress_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return CompressOptions(
      maxBytes: dco_decode_u_32(arr[0]),
      maxWidth: dco_decode_opt_box_autoadd_u_32(arr[1]),
      maxHeight: dco_decode_opt_box_autoadd_u_32(arr[2]),
      format: dco_decode_output_format(arr[3]),
      minQuality: dco_decode_u_8(arr[4]),
      maxQuality: dco_decode_u_8(arr[5]),
      minDimension: dco_decode_u_32(arr[6]),
      keepOriginalIfFits: dco_decode_bool(arr[7]),
      stripMetadata: dco_decode_bool(arr[8]),
    );
  }

  @protected
  CompressResult dco_decode_compress_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return CompressResult(
      bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      sizeBytes: dco_decode_u_32(arr[1]),
      width: dco_decode_u_32(arr[2]),
      height: dco_decode_u_32(arr[3]),
      format: dco_decode_output_format(arr[4]),
      quality: dco_decode_opt_box_autoadd_u_8(arr[5]),
      originalSizeBytes: dco_decode_u_32(arr[6]),
      originalWidth: dco_decode_u_32(arr[7]),
      originalHeight: dco_decode_u_32(arr[8]),
      originalFormat: dco_decode_input_format(arr[9]),
      keptOriginal: dco_decode_bool(arr[10]),
      attempts: dco_decode_u_32(arr[11]),
      elapsedMs: dco_decode_u_32(arr[12]),
    );
  }

  @protected
  ErrorCode dco_decode_error_code(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ErrorCode.values[raw as int];
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ImageGuardError dco_decode_image_guard_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ImageGuardError(
      code: dco_decode_error_code(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  ImageInfo dco_decode_image_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ImageInfo(
      format: dco_decode_input_format(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      sizeBytes: dco_decode_u_32(arr[3]),
      hasOrientation: dco_decode_bool(arr[4]),
    );
  }

  @protected
  InputFormat dco_decode_input_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return InputFormat.values[raw as int];
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  CompressResult? dco_decode_opt_box_autoadd_compress_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_compress_result(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  OutputFormat dco_decode_output_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OutputFormat.values[raw as int];
  }

  @protected
  ProcessResult dco_decode_process_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ProcessResult(
      safety: dco_decode_safety_report(arr[0]),
      image: dco_decode_opt_box_autoadd_compress_result(arr[1]),
    );
  }

  @protected
  SafetyOptions dco_decode_safety_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SafetyOptions(
      rejectThreshold: dco_decode_f_32(arr[0]),
      reviewThreshold: dco_decode_f_32(arr[1]),
      suggestiveWeight: dco_decode_f_32(arr[2]),
      compressUnsafe: dco_decode_bool(arr[3]),
    );
  }

  @protected
  SafetyReport dco_decode_safety_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SafetyReport(
      verdict: dco_decode_verdict(arr[0]),
      nsfwScore: dco_decode_f_32(arr[1]),
      scores: dco_decode_safety_scores(arr[2]),
      elapsedMs: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  SafetyScores dco_decode_safety_scores(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SafetyScores(
      drawings: dco_decode_f_32(arr[0]),
      hentai: dco_decode_f_32(arr[1]),
      neutral: dco_decode_f_32(arr[2]),
      porn: dco_decode_f_32(arr[3]),
      sexy: dco_decode_f_32(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  Verdict dco_decode_verdict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Verdict.values[raw as int];
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CompressOptions sse_decode_box_autoadd_compress_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_compress_options(deserializer));
  }

  @protected
  CompressResult sse_decode_box_autoadd_compress_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_compress_result(deserializer));
  }

  @protected
  SafetyOptions sse_decode_box_autoadd_safety_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_safety_options(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  CompressOptions sse_decode_compress_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_maxBytes = sse_decode_u_32(deserializer);
    var var_maxWidth = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_maxHeight = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_format = sse_decode_output_format(deserializer);
    var var_minQuality = sse_decode_u_8(deserializer);
    var var_maxQuality = sse_decode_u_8(deserializer);
    var var_minDimension = sse_decode_u_32(deserializer);
    var var_keepOriginalIfFits = sse_decode_bool(deserializer);
    var var_stripMetadata = sse_decode_bool(deserializer);
    return CompressOptions(
      maxBytes: var_maxBytes,
      maxWidth: var_maxWidth,
      maxHeight: var_maxHeight,
      format: var_format,
      minQuality: var_minQuality,
      maxQuality: var_maxQuality,
      minDimension: var_minDimension,
      keepOriginalIfFits: var_keepOriginalIfFits,
      stripMetadata: var_stripMetadata,
    );
  }

  @protected
  CompressResult sse_decode_compress_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_sizeBytes = sse_decode_u_32(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_format = sse_decode_output_format(deserializer);
    var var_quality = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_originalSizeBytes = sse_decode_u_32(deserializer);
    var var_originalWidth = sse_decode_u_32(deserializer);
    var var_originalHeight = sse_decode_u_32(deserializer);
    var var_originalFormat = sse_decode_input_format(deserializer);
    var var_keptOriginal = sse_decode_bool(deserializer);
    var var_attempts = sse_decode_u_32(deserializer);
    var var_elapsedMs = sse_decode_u_32(deserializer);
    return CompressResult(
      bytes: var_bytes,
      sizeBytes: var_sizeBytes,
      width: var_width,
      height: var_height,
      format: var_format,
      quality: var_quality,
      originalSizeBytes: var_originalSizeBytes,
      originalWidth: var_originalWidth,
      originalHeight: var_originalHeight,
      originalFormat: var_originalFormat,
      keptOriginal: var_keptOriginal,
      attempts: var_attempts,
      elapsedMs: var_elapsedMs,
    );
  }

  @protected
  ErrorCode sse_decode_error_code(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ErrorCode.values[inner];
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  ImageGuardError sse_decode_image_guard_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_error_code(deserializer);
    var var_message = sse_decode_String(deserializer);
    return ImageGuardError(code: var_code, message: var_message);
  }

  @protected
  ImageInfo sse_decode_image_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_format = sse_decode_input_format(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_sizeBytes = sse_decode_u_32(deserializer);
    var var_hasOrientation = sse_decode_bool(deserializer);
    return ImageInfo(
      format: var_format,
      width: var_width,
      height: var_height,
      sizeBytes: var_sizeBytes,
      hasOrientation: var_hasOrientation,
    );
  }

  @protected
  InputFormat sse_decode_input_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return InputFormat.values[inner];
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  CompressResult? sse_decode_opt_box_autoadd_compress_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_compress_result(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OutputFormat sse_decode_output_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return OutputFormat.values[inner];
  }

  @protected
  ProcessResult sse_decode_process_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_safety = sse_decode_safety_report(deserializer);
    var var_image = sse_decode_opt_box_autoadd_compress_result(deserializer);
    return ProcessResult(safety: var_safety, image: var_image);
  }

  @protected
  SafetyOptions sse_decode_safety_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rejectThreshold = sse_decode_f_32(deserializer);
    var var_reviewThreshold = sse_decode_f_32(deserializer);
    var var_suggestiveWeight = sse_decode_f_32(deserializer);
    var var_compressUnsafe = sse_decode_bool(deserializer);
    return SafetyOptions(
      rejectThreshold: var_rejectThreshold,
      reviewThreshold: var_reviewThreshold,
      suggestiveWeight: var_suggestiveWeight,
      compressUnsafe: var_compressUnsafe,
    );
  }

  @protected
  SafetyReport sse_decode_safety_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_verdict = sse_decode_verdict(deserializer);
    var var_nsfwScore = sse_decode_f_32(deserializer);
    var var_scores = sse_decode_safety_scores(deserializer);
    var var_elapsedMs = sse_decode_u_32(deserializer);
    return SafetyReport(
      verdict: var_verdict,
      nsfwScore: var_nsfwScore,
      scores: var_scores,
      elapsedMs: var_elapsedMs,
    );
  }

  @protected
  SafetyScores sse_decode_safety_scores(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_drawings = sse_decode_f_32(deserializer);
    var var_hentai = sse_decode_f_32(deserializer);
    var var_neutral = sse_decode_f_32(deserializer);
    var var_porn = sse_decode_f_32(deserializer);
    var var_sexy = sse_decode_f_32(deserializer);
    return SafetyScores(
      drawings: var_drawings,
      hentai: var_hentai,
      neutral: var_neutral,
      porn: var_porn,
      sexy: var_sexy,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  Verdict sse_decode_verdict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Verdict.values[inner];
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_compress_options(
    CompressOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_compress_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_compress_result(
    CompressResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_compress_result(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_safety_options(
    SafetyOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_safety_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_compress_options(
    CompressOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.maxBytes, serializer);
    sse_encode_opt_box_autoadd_u_32(self.maxWidth, serializer);
    sse_encode_opt_box_autoadd_u_32(self.maxHeight, serializer);
    sse_encode_output_format(self.format, serializer);
    sse_encode_u_8(self.minQuality, serializer);
    sse_encode_u_8(self.maxQuality, serializer);
    sse_encode_u_32(self.minDimension, serializer);
    sse_encode_bool(self.keepOriginalIfFits, serializer);
    sse_encode_bool(self.stripMetadata, serializer);
  }

  @protected
  void sse_encode_compress_result(
    CompressResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_u_32(self.sizeBytes, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_output_format(self.format, serializer);
    sse_encode_opt_box_autoadd_u_8(self.quality, serializer);
    sse_encode_u_32(self.originalSizeBytes, serializer);
    sse_encode_u_32(self.originalWidth, serializer);
    sse_encode_u_32(self.originalHeight, serializer);
    sse_encode_input_format(self.originalFormat, serializer);
    sse_encode_bool(self.keptOriginal, serializer);
    sse_encode_u_32(self.attempts, serializer);
    sse_encode_u_32(self.elapsedMs, serializer);
  }

  @protected
  void sse_encode_error_code(ErrorCode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_image_guard_error(
    ImageGuardError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_error_code(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_image_info(ImageInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_input_format(self.format, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_u_32(self.sizeBytes, serializer);
    sse_encode_bool(self.hasOrientation, serializer);
  }

  @protected
  void sse_encode_input_format(InputFormat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_compress_result(
    CompressResult? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_compress_result(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_output_format(OutputFormat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_process_result(ProcessResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_safety_report(self.safety, serializer);
    sse_encode_opt_box_autoadd_compress_result(self.image, serializer);
  }

  @protected
  void sse_encode_safety_options(SafetyOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.rejectThreshold, serializer);
    sse_encode_f_32(self.reviewThreshold, serializer);
    sse_encode_f_32(self.suggestiveWeight, serializer);
    sse_encode_bool(self.compressUnsafe, serializer);
  }

  @protected
  void sse_encode_safety_report(SafetyReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_verdict(self.verdict, serializer);
    sse_encode_f_32(self.nsfwScore, serializer);
    sse_encode_safety_scores(self.scores, serializer);
    sse_encode_u_32(self.elapsedMs, serializer);
  }

  @protected
  void sse_encode_safety_scores(SafetyScores self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.drawings, serializer);
    sse_encode_f_32(self.hentai, serializer);
    sse_encode_f_32(self.neutral, serializer);
    sse_encode_f_32(self.porn, serializer);
    sse_encode_f_32(self.sexy, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_verdict(Verdict self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
