// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

Future<CompressResult> compressFile({
  required String path,
  required CompressOptions options,
}) => RustLib.instance.api.crateApiCompressCompressFile(
  path: path,
  options: options,
);

Future<CompressResult> compressBytes({
  required List<int> bytes,
  required CompressOptions options,
}) => RustLib.instance.api.crateApiCompressCompressBytes(
  bytes: bytes,
  options: options,
);

Future<ImageInfo> imageInfoFile({required String path}) =>
    RustLib.instance.api.crateApiCompressImageInfoFile(path: path);

Future<ImageInfo> imageInfoBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiCompressImageInfoBytes(bytes: bytes);

/// Cheap check so Dart can reject bad options before reading any file.
void validateCompressOptions({required CompressOptions options}) => RustLib
    .instance
    .api
    .crateApiCompressValidateCompressOptions(options: options);
