// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Loads (or replaces) the ONNX model. Takes ~100–300 ms; call once.
Future<void> loadModel({required List<int> model}) =>
    RustLib.instance.api.crateApiSafetyLoadModel(model: model);

bool isModelLoaded() => RustLib.instance.api.crateApiSafetyIsModelLoaded();

/// Frees the model memory. `load_model` must be called again before use.
void unloadModel() => RustLib.instance.api.crateApiSafetyUnloadModel();

Future<SafetyReport> classifyFile({
  required String path,
  required SafetyOptions safety,
}) =>
    RustLib.instance.api.crateApiSafetyClassifyFile(path: path, safety: safety);

Future<SafetyReport> classifyBytes({
  required List<int> bytes,
  required SafetyOptions safety,
}) => RustLib.instance.api.crateApiSafetyClassifyBytes(
  bytes: bytes,
  safety: safety,
);

Future<ProcessResult> processFile({
  required String path,
  required CompressOptions options,
  required SafetyOptions safety,
}) => RustLib.instance.api.crateApiSafetyProcessFile(
  path: path,
  options: options,
  safety: safety,
);

Future<ProcessResult> processBytes({
  required List<int> bytes,
  required CompressOptions options,
  required SafetyOptions safety,
}) => RustLib.instance.api.crateApiSafetyProcessBytes(
  bytes: bytes,
  options: options,
  safety: safety,
);
