// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Everything the caller can tune. All values are validated by
/// [`crate::core::validate::validate_options`] before any work is done.
class CompressOptions {
  /// Hard upper limit for the output size in bytes.
  final int maxBytes;

  /// Output will be at most this wide (aspect ratio is kept, never upscaled).
  final int? maxWidth;

  /// Output will be at most this tall (aspect ratio is kept, never upscaled).
  final int? maxHeight;
  final OutputFormat format;

  /// Lowest JPEG quality the search may use (1–100).
  final int minQuality;

  /// Highest JPEG quality the search may use (1–100).
  final int maxQuality;

  /// The search never shrinks the longest side below this many pixels;
  /// if the target still cannot be met, `CannotMeetTarget` is returned.
  final int minDimension;

  /// If the input already satisfies every limit (size, resolution, format)
  /// it is returned as-is instead of being re-encoded.
  final bool keepOriginalIfFits;

  /// Remove EXIF/XMP/IPTC/text metadata (e.g. GPS location).
  final bool stripMetadata;

  const CompressOptions({
    required this.maxBytes,
    this.maxWidth,
    this.maxHeight,
    required this.format,
    required this.minQuality,
    required this.maxQuality,
    required this.minDimension,
    required this.keepOriginalIfFits,
    required this.stripMetadata,
  });

  static Future<CompressOptions> default_() =>
      RustLib.instance.api.crateApiTypesCompressOptionsDefault();

  @override
  int get hashCode =>
      maxBytes.hashCode ^
      maxWidth.hashCode ^
      maxHeight.hashCode ^
      format.hashCode ^
      minQuality.hashCode ^
      maxQuality.hashCode ^
      minDimension.hashCode ^
      keepOriginalIfFits.hashCode ^
      stripMetadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompressOptions &&
          runtimeType == other.runtimeType &&
          maxBytes == other.maxBytes &&
          maxWidth == other.maxWidth &&
          maxHeight == other.maxHeight &&
          format == other.format &&
          minQuality == other.minQuality &&
          maxQuality == other.maxQuality &&
          minDimension == other.minDimension &&
          keepOriginalIfFits == other.keepOriginalIfFits &&
          stripMetadata == other.stripMetadata;
}

class CompressResult {
  final Uint8List bytes;
  final int sizeBytes;
  final int width;
  final int height;
  final OutputFormat format;

  /// JPEG quality that was used; `None` for PNG or when the original was kept.
  final int? quality;
  final int originalSizeBytes;

  /// Width/height of the input after EXIF orientation was applied.
  final int originalWidth;
  final int originalHeight;
  final InputFormat originalFormat;

  /// `true` when the input already fit and was returned without re-encoding.
  final bool keptOriginal;

  /// Number of encode attempts the size search needed.
  final int attempts;
  final int elapsedMs;

  const CompressResult({
    required this.bytes,
    required this.sizeBytes,
    required this.width,
    required this.height,
    required this.format,
    this.quality,
    required this.originalSizeBytes,
    required this.originalWidth,
    required this.originalHeight,
    required this.originalFormat,
    required this.keptOriginal,
    required this.attempts,
    required this.elapsedMs,
  });

  @override
  int get hashCode =>
      bytes.hashCode ^
      sizeBytes.hashCode ^
      width.hashCode ^
      height.hashCode ^
      format.hashCode ^
      quality.hashCode ^
      originalSizeBytes.hashCode ^
      originalWidth.hashCode ^
      originalHeight.hashCode ^
      originalFormat.hashCode ^
      keptOriginal.hashCode ^
      attempts.hashCode ^
      elapsedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompressResult &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          sizeBytes == other.sizeBytes &&
          width == other.width &&
          height == other.height &&
          format == other.format &&
          quality == other.quality &&
          originalSizeBytes == other.originalSizeBytes &&
          originalWidth == other.originalWidth &&
          originalHeight == other.originalHeight &&
          originalFormat == other.originalFormat &&
          keptOriginal == other.keptOriginal &&
          attempts == other.attempts &&
          elapsedMs == other.elapsedMs;
}

enum ErrorCode {
  invalidOptions,
  emptyInput,
  fileNotFound,
  fileReadFailed,
  inputTooLarge,
  unsupportedFormat,
  corruptImage,
  imageTooLarge,
  cannotMeetTarget,
  encodingFailed,

  /// `classify`/`process` was called before the NSFW model was loaded.
  modelNotLoaded,

  /// The model bytes are not a valid ONNX model of the expected shape.
  modelLoadFailed,
  internal,
}

class ImageGuardError implements FrbException {
  final ErrorCode code;
  final String message;

  const ImageGuardError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageGuardError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

class ImageInfo {
  final InputFormat format;

  /// Width/height after EXIF orientation.
  final int width;
  final int height;
  final int sizeBytes;

  /// `true` when the image has an EXIF rotation/flip that viewers apply.
  final bool hasOrientation;

  const ImageInfo({
    required this.format,
    required this.width,
    required this.height,
    required this.sizeBytes,
    required this.hasOrientation,
  });

  @override
  int get hashCode =>
      format.hashCode ^
      width.hashCode ^
      height.hashCode ^
      sizeBytes.hashCode ^
      hasOrientation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageInfo &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          width == other.width &&
          height == other.height &&
          sizeBytes == other.sizeBytes &&
          hasOrientation == other.hasOrientation;
}

/// Format detected from the input bytes.
enum InputFormat { jpeg, png, webP, gif, bmp }

/// Output encoding.
enum OutputFormat {
  /// Lossy. Size is controlled by quality first, then by resolution.
  jpeg,

  /// Lossless. Size is controlled by resolution only (quality is ignored).
  png,
}

class ProcessResult {
  final SafetyReport safety;

  /// `None` when the image was unsafe and `compress_unsafe` is false.
  final CompressResult? image;

  const ProcessResult({required this.safety, this.image});

  @override
  int get hashCode => safety.hashCode ^ image.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessResult &&
          runtimeType == other.runtimeType &&
          safety == other.safety &&
          image == other.image;
}

/// How the NSFW scores are turned into a decision.
class SafetyOptions {
  /// `nsfw_score >= reject_threshold` → [`Verdict::Unsafe`]. Range 0–1.
  final double rejectThreshold;

  /// `nsfw_score >= review_threshold` → [`Verdict::Uncertain`]. Range 0–1, ≤ reject.
  final double reviewThreshold;

  /// How much the `sexy` (suggestive) class counts towards `nsfw_score`. Range 0–1.
  final double suggestiveWeight;

  /// Also compress images judged unsafe (normally skipped to save time).
  final bool compressUnsafe;

  const SafetyOptions({
    required this.rejectThreshold,
    required this.reviewThreshold,
    required this.suggestiveWeight,
    required this.compressUnsafe,
  });

  static Future<SafetyOptions> default_() =>
      RustLib.instance.api.crateApiTypesSafetyOptionsDefault();

  @override
  int get hashCode =>
      rejectThreshold.hashCode ^
      reviewThreshold.hashCode ^
      suggestiveWeight.hashCode ^
      compressUnsafe.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SafetyOptions &&
          runtimeType == other.runtimeType &&
          rejectThreshold == other.rejectThreshold &&
          reviewThreshold == other.reviewThreshold &&
          suggestiveWeight == other.suggestiveWeight &&
          compressUnsafe == other.compressUnsafe;
}

class SafetyReport {
  final Verdict verdict;

  /// `porn + hentai + sexy × suggestive_weight`, clamped to 0–1.
  final double nsfwScore;
  final SafetyScores scores;
  final int elapsedMs;

  const SafetyReport({
    required this.verdict,
    required this.nsfwScore,
    required this.scores,
    required this.elapsedMs,
  });

  @override
  int get hashCode =>
      verdict.hashCode ^
      nsfwScore.hashCode ^
      scores.hashCode ^
      elapsedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SafetyReport &&
          runtimeType == other.runtimeType &&
          verdict == other.verdict &&
          nsfwScore == other.nsfwScore &&
          scores == other.scores &&
          elapsedMs == other.elapsedMs;
}

/// Raw model probabilities (they sum to ~1).
class SafetyScores {
  final double drawings;
  final double hentai;
  final double neutral;
  final double porn;
  final double sexy;

  const SafetyScores({
    required this.drawings,
    required this.hentai,
    required this.neutral,
    required this.porn,
    required this.sexy,
  });

  @override
  int get hashCode =>
      drawings.hashCode ^
      hentai.hashCode ^
      neutral.hashCode ^
      porn.hashCode ^
      sexy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SafetyScores &&
          runtimeType == other.runtimeType &&
          drawings == other.drawings &&
          hentai == other.hentai &&
          neutral == other.neutral &&
          porn == other.porn &&
          sexy == other.sexy;
}

enum Verdict {
  safe,

  /// Between the review and reject thresholds: the app decides.
  uncertain,
  unsafe,
}
