// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Everything the caller can tune. All values are validated by
/// [`crate::core::validate::validate_options`] before any work is done.
class CompressOptions {
  /// Hard upper limit for the output size in bytes.
  final int maxBytes;

  /// Output will be at most this wide (aspect ratio is kept, never upscaled).
  final int? maxWidth;

  /// Output will be at most this tall (aspect ratio is kept, never upscaled).
  final int? maxHeight;
  final OutputFormat format;

  /// Lowest JPEG quality the search may use (1–100).
  final int minQuality;

  /// Highest JPEG quality the search may use (1–100).
  final int maxQuality;

  /// The search never shrinks the longest side below this many pixels;
  /// if the target still cannot be met, `CannotMeetTarget` is returned.
  final int minDimension;

  /// If the input already satisfies every limit (size, resolution, format)
  /// it is returned as-is instead of being re-encoded.
  final bool keepOriginalIfFits;

  /// Remove EXIF/XMP/IPTC/text metadata (e.g. GPS location).
  final bool stripMetadata;

  const CompressOptions({
    required this.maxBytes,
    this.maxWidth,
    this.maxHeight,
    required this.format,
    required this.minQuality,
    required this.maxQuality,
    required this.minDimension,
    required this.keepOriginalIfFits,
    required this.stripMetadata,
  });

  static Future<CompressOptions> default_() =>
      RustLib.instance.api.crateApiTypesCompressOptionsDefault();

  @override
  int get hashCode =>
      maxBytes.hashCode ^
      maxWidth.hashCode ^
      maxHeight.hashCode ^
      format.hashCode ^
      minQuality.hashCode ^
      maxQuality.hashCode ^
      minDimension.hashCode ^
      keepOriginalIfFits.hashCode ^
      stripMetadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompressOptions &&
          runtimeType == other.runtimeType &&
          maxBytes == other.maxBytes &&
          maxWidth == other.maxWidth &&
          maxHeight == other.maxHeight &&
          format == other.format &&
          minQuality == other.minQuality &&
          maxQuality == other.maxQuality &&
          minDimension == other.minDimension &&
          keepOriginalIfFits == other.keepOriginalIfFits &&
          stripMetadata == other.stripMetadata;
}

class CompressResult {
  final Uint8List bytes;
  final int sizeBytes;
  final int width;
  final int height;
  final OutputFormat format;

  /// JPEG quality that was used; `None` for PNG or when the original was kept.
  final int? quality;
  final int originalSizeBytes;

  /// Width/height of the input after EXIF orientation was applied.
  final int originalWidth;
  final int originalHeight;
  final InputFormat originalFormat;

  /// `true` when the input already fit and was returned without re-encoding.
  final bool keptOriginal;

  /// Number of encode attempts the size search needed.
  final int attempts;
  final int elapsedMs;

  const CompressResult({
    required this.bytes,
    required this.sizeBytes,
    required this.width,
    required this.height,
    required this.format,
    this.quality,
    required this.originalSizeBytes,
    required this.originalWidth,
    required this.originalHeight,
    required this.originalFormat,
    required this.keptOriginal,
    required this.attempts,
    required this.elapsedMs,
  });

  @override
  int get hashCode =>
      bytes.hashCode ^
      sizeBytes.hashCode ^
      width.hashCode ^
      height.hashCode ^
      format.hashCode ^
      quality.hashCode ^
      originalSizeBytes.hashCode ^
      originalWidth.hashCode ^
      originalHeight.hashCode ^
      originalFormat.hashCode ^
      keptOriginal.hashCode ^
      attempts.hashCode ^
      elapsedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompressResult &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          sizeBytes == other.sizeBytes &&
          width == other.width &&
          height == other.height &&
          format == other.format &&
          quality == other.quality &&
          originalSizeBytes == other.originalSizeBytes &&
          originalWidth == other.originalWidth &&
          originalHeight == other.originalHeight &&
          originalFormat == other.originalFormat &&
          keptOriginal == other.keptOriginal &&
          attempts == other.attempts &&
          elapsedMs == other.elapsedMs;
}

enum ErrorCode {
  invalidOptions,
  emptyInput,
  fileNotFound,
  fileReadFailed,
  inputTooLarge,
  unsupportedFormat,
  corruptImage,
  imageTooLarge,
  cannotMeetTarget,
  encodingFailed,
  internal,
}

class ImageGuardError implements FrbException {
  final ErrorCode code;
  final String message;

  const ImageGuardError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageGuardError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

class ImageInfo {
  final InputFormat format;

  /// Width/height after EXIF orientation.
  final int width;
  final int height;
  final int sizeBytes;

  /// `true` when the image has an EXIF rotation/flip that viewers apply.
  final bool hasOrientation;

  const ImageInfo({
    required this.format,
    required this.width,
    required this.height,
    required this.sizeBytes,
    required this.hasOrientation,
  });

  @override
  int get hashCode =>
      format.hashCode ^
      width.hashCode ^
      height.hashCode ^
      sizeBytes.hashCode ^
      hasOrientation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageInfo &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          width == other.width &&
          height == other.height &&
          sizeBytes == other.sizeBytes &&
          hasOrientation == other.hasOrientation;
}

/// Format detected from the input bytes.
enum InputFormat { jpeg, png, webP, gif, bmp }

/// Output encoding.
enum OutputFormat {
  /// Lossy. Size is controlled by quality first, then by resolution.
  jpeg,

  /// Lossless. Size is controlled by resolution only (quality is ignored).
  png,
}
